CREATE DATABASE `convenios` /*!40100 DEFAULT CHARACTER SET utf8 */;

use  `convenios`;

CREATE TABLE convenios.TIPO_FOO 
	(	ID INTEGER AUTO_INCREMENT NOT NULL, 
		DESCRIPCION VARCHAR(255) NOT NULL, 
		CONSTRAINT PK_SUB_FOO PRIMARY KEY (ID));